title: About Me
author: Prash Katukojwala
remote_theme: jekyll/minima@3cdd14d
minima:
    skin: dark
plugins:
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
